name: '11'
favicon: null
layout_spectrum: 0.9612056037876755
typography_spectrum: 0.5458533994387835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9879164090380073
  lightness: 0.2583191602025181
  saturation: 0.7100003641098738
  rhythmicContrast: 0.21700929081998765
purpose: []
